=== tootal/vnote/src/data/extra/tasks/schema/task.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "task.json",
    "title": "Task",
    "description": "A flexible task system for VNote",
    "type": "object",
    "properties": {
        "version": {
            "description": "The configuration's version number.",
            "type": "string"
        },
        "label": {
            "description": "The task's name.",
            "$ref": "locale.json"
        },
        "icon": {
            "description": "The task's icon.",
            "type": "string"
        },
        "shortcut": {
            "description": "The task's shortcut.",
            "type": "string"
        },
        "type": {
            "description": "The type of a custom task.",
            "type": "string",
            "enum": ["shell", "process"]
        },
        "command": {
            "description": "The command to be executed.",
            "$ref": "locale.json"
        },
        "args": {
            "description": "The arguments passed to the command.",
            "type": "array",
            "items": {
                "$ref": "locale.json"
            }
        },
        "options": {
            "description": "The command options used when the command is executed.",
            "$ref": "options.json"
        },
        "inputs": {
            "description": "The configuration of the input variables.",
            "type": "array",
            "items": {
                "$ref": "input.json"
            }
        },
        "windows": {
            "description": "Windows specific task configuration.",
            "$ref": "task.json"
        },
        "linux": {
            "description": "Linux specific task configuration.",
            "$ref": "task.json"
        },
        "osx": {
            "description": "macOS specific task configuration.",
            "$ref": "task.json"
        },
        "tasks": {
            "description": "The configuration of the available tasks.",
            "type": "array",
            "items": {
                "$ref": "task.json"
            }
        }
    }
}

=== tootal/vnote/src/data/extra/tasks/sample.json
{
    "version": "0.1.5",
    "label": "Sample",
    "icon": "sample.svg",
    "shortcut": "Alt+G, S",
    "command": "echo",
    "args": [
        {
            "en_US": "hello",
            "zh_CN": "你好"
        }
    ],
    "options": {
        "cwd": "${taskDirname}",
        "env": {
            "key": "value"
        },
        "shell": {
            "executable": "/bin/bash",
            "args": [
                "-c"
            ]
        }
    }
}
